name: libc
description: C Standard Library

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  ffi: ^1.1.2
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  ffigen: ^4.1.3
  lints: ^1.0.0
  test: ^1.16.0
