name: stdlibc
description: C Standard Library

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  ffi: ^2.0.1
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.11
  ffigen: ^6.0.1
  lints: ^2.0.0
  macro_builder:
    path: tool/macro_builder
  test: ^1.16.0
